dist: xenial

python:
  - "3.6"

services:
  - postgresql
addons:
  postgresql: "9.4"
  chrome: "stable"

notifications:
  email:
    recipients:
    - angelpomaresus@gmail.com
    - anyelo1990@hotmail.com
    on_success: always
    on_failure: always
branches:
  only:
    - master
    - pruebacambios
    - practica7

before_script:
  - cp  decide/local_settings.travis.py decide/local_settings.py
  - psql -U postgres -c "create user decide password 'decide'"
  - psql -U postgres -c "create database test_decide owner decide"
  - psql -U postgres -c "ALTER USER decide CREATEDB"
  - python decide/manage.py migrate
language: python

before install:
  - wget https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver
install:
  - pip install -r requirements.txt
  - pip install codacy-coverage
  - pip install selenium
script:
  - cd decide
  #- coverage run --branch --source=. ./manage.py test --keepdb --with-xunit
  #- coverage xml
  #- python-codacy-coverage -r coverage.xml
  - python3 ./manage.py test authentication/testsSelenium.py -v 2
deploy:
  provider: heroku
  app: angpomluz-egc-p7
  strategy: git
  apikey: $HEROKU_AUTH_TOKEN
